tests_news = [
    {'site': 'Carta Capital',
    'title_news': 'Título Notícia Carta Capital data',
    'url_news': 'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2023/02/27/sp-prefeitura-sugere-mudar-lei-para-frear-construcao-de-microapartamentos.htm',
    'tag': 'Gerais',
    'img_src': './images/carta_capital_logo.png',
    'score_tb': 0.2,
    'sentiment_tb': 'positivo',
    'score_subjectivity': 0.1,
    'subjectivity_tb': 'neutro',
    'espectro': 'left'
    },
    {'site': 'ICL Notícias',
    'title_news': 'Título Notícia ICL data',
    'url_news': 'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2023/02/27/sp-prefeitura-sugere-mudar-lei-para-frear-construcao-de-microapartamentos.htm',
    'tag': 'Gerais',
    'img_src': './images/icl_logo.png',
    'score_tb': 0.3,
    'sentiment_tb': 'positivo',
    'score_subjectivity': 0.7,
    'subjectivity_tb': 'objetivo',
    'espectro': 'left'
    },
    {'site': 'Poder 360',
    'title_news': 'Título Notícia Poder 360 data',
    'url_news': 'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2023/02/27/sp-prefeitura-sugere-mudar-lei-para-frear-construcao-de-microapartamentos.htm',
    'tag': 'Gerais',
    'img_src': './images/poder_360_logo.png',
    'score_tb': 0.3,
    'sentiment_tb': 'positivo',
    'score_subjectivity': 0.7,
    'subjectivity_tb': 'objetivo',
    'espectro': 'center'
    },
    {'site': 'UOL',
    'title_news': 'Título Notícia Uol data',
    'url_news': 'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2023/02/27/sp-prefeitura-sugere-mudar-lei-para-frear-construcao-de-microapartamentos.htm',
    'tag': 'Gerais',
    'img_src': 'images/uol_logo.png',
    'score_tb': 0.3,
    'sentiment_tb': 'positivo',
    'score_subjectivity': 0.7,
    'subjectivity_tb': 'objetivo',
    'espectro': 'right'
    },
    {'site': 'G1-Mundo',
    'title_news': 'Entenda o que significa o acordo da ONU para proteger a vida marinha em alto-mar',
    'url_news': 'https://g1.globo.com/mundo/noticia/2023/03/05/entenda-o-que-significa-o-acordo-da-onu-para-proteger-a-vida-marinha-em-alto-mar.ghtml',
    'tag': 'Gerais',
    'img_src': 'images/g1_logo.png',
    'score_tb': 0.3,
    'sentiment_tb': 'positivo',
    'score_subjectivity': 0.7,
    'subjectivity_tb': 'objetivo',
    'espectro': 'right'
    },
    {'site': 'Canaltech',
    'title_news': 'O que era a esfera metálica que apareceu na praia do Japão?',
    'url_news': 'https://canaltech.com.br/meio-ambiente/o-que-era-a-esfera-metalica-que-apareceu-na-praia-do-japao-241154/',
    'tag': 'Tecnologia',
    'img_src': 'images/canaltech_logo.png',
    'score_tb': 0.3,
    'sentiment_tb': 'positivo',
    'score_subjectivity': 0.7,
    'subjectivity_tb': 'objetivo',
    'espectro': 'right'
    },
    {'site': 'Olhar digital',
    'title_news': 'A ciência por trás da sinuca [vídeo]',
    'url_news': 'https://www.tecmundo.com.br/esporte/18051-a-ciencia-por-tras-da-sinuca-video-.htm',
    'tag': 'Esportes',
    'img_src': 'images/tecmundo_logo.png',
    'score_tb': 0.3,
    'sentiment_tb': 'positivo',
    'score_subjectivity': 0.7,
    'subjectivity_tb': 'objetivo',
    'espectro': 'right'
    } 
]